### ISSUE TITLE
Preposiciones 

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Paola939#1]
[Practica_preposiciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Paola939/files/13185404/Practica_preposiciones.pdf)

**Comment by bibiana-m** [comment]
Portadas: 25%
Procedimientos: 25%
Figuras e ilustraciones: 25%
Resultado y conclusiones: 25%
Calificación: 100% / 10 * 20 = 20

Comentario: Favor de usar más colores para subrayar.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
